groups:
  md_5:
  - admin
disabled_commands:
player_limit: -1
stats: 30d05be4-ed9c-4a67-bae8-85cf577a3e5e
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners:
- max_players: 1
  fallback_server: lobby
  host: 0.0.0.0:25577
  bind_local_address: true
  ping_passthrough: false
  tab_list: GLOBAL_PING
  default_server: lobby
  forced_hosts:
    pvp.md-5.net: pvp
  tab_size: 60
  force_default_server: false
  motd: '&1Another Bungee server'
  query_enabled: false
  query_port: 25577
timeout: 30000
connection_throttle: 4000
servers:
  lobby:
    address: jaalon.org:25567
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
ip_forward: false
online_mode: true
